Custom_users/urls.py
# from turtle import home
from django.contrib import admin
from django.urls import path

from .views import *

app_name = 'Custom_users'

urlpatterns = [
   path('pp/',PatientSignUpView,name='patientRegister'),
#    path('home/',home,name='home'),
   path('profile/', profile, name='profile'),

    path('profile-edit/', profile_edit, name='profile-edit'),

    path('orders-by-user/', orders_by_user, name='orders-by-user'),

    path('filtered-reports-by-user/<int:id>/', filtered_report, name='filtered-reports-by-user')

]

Flightmode/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
# from custom_users import urls 
# from .views import home
# from .views import DevelopersView

urlpatterns = [
    path('admin/', admin.site.urls),
    # App1 (diagnostic_centers)
    path('',include('Custom_users.urls')),
    # App2 (diagnostic_centers)
    path('',include('Doctor_user.urls')),
    # App3 (diagnostic_centers)
    path('', include('diagnostic_centers.urls', namespace='diagnostic_centers')),

    # App4 (tests)
    path('', include('tests.urls', namespace='tests')),

    # App4 (report_processing)
    path('', include('report_processing.urls', namespace='report_processing')),

    path('',include('portal.urls'))

    # Allauth (built-in)
    # path('accounts/', include('allauth.urls')),

    # # Developers
    # path('developers/', DevelopersView.as_view(), name='developers'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diagnostic_centers/urls.py
from django.urls import path

from .views import *
# (

#     search_paginator,

#     admin_login,
#     admin_logout,
#     admin_dashboard,

#     staff_login,
#     staff_logout,
#     staff_dashboard,

#     center_details,

# )


app_name = 'diagnostic_centers'

urlpatterns = [

    path('all-centers/', search_paginator, name='all-centers'),

    path('admin-login/', admin_login, name='admin-login'),
    path('admin-logout/', admin_logout, name='admin-logout'),
    path('admin-dashboard/<username>/', admin_dashboard, name='admin-dashboard'),

    path('staff-login/', staff_login, name='staff-login'),
    path('staff-logout/', staff_logout, name='staff-logout'),
    path('staff-dashboard/<username>/', staff_dashboard, name='staff-dashboard'),
    path('staff-dashboard/<int:id>/<username>/', staff_dashboard, name='staff-dashboards'),

    path('center-details/<int:id>/', center_details, name='center-details'),


]

portal/urls.py
# from turtle import home
# from django.contrib import admin
from django.urls import path

from .views import *

app_name = 'portal'

urlpatterns = [
   path('',home,name="home"),
]

templates/ok/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
	<title>{% block title %}{% endblock %}</title>

	<!-- fontawesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.0/css/all.css"
		integrity="sha384-Mmxa0mLqhmOeaE8vgOSbKacftZcsNYDjQzuCOm6D02luYSzBG8vpaOykv9lFQ51Y" crossorigin="anonymous">


	<link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/fakeLoader.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

	<script src="{% static 'js/jquery.min.js' %}"></script>

</head>

<body>

	<!-- loader -->
	<div class="fakeLoader"></div>
	<!-- loader -->


	<nav class="navbar navbar-expand-lg">
		<div class="container">
			{% comment %} <a class="navbar-brand text-white" href="{% url 'home' %}"><b>ODLRS</b></a> {% endcomment %}
			<button class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent"
				aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<!-- <span class="navbar-toggler-icon"></span> -->
				<i class="fa fa-bars text-white"></i>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item ">
						{% comment %} <a class="nav-link" href="{% url 'home' %}">Home</a> {% endcomment %}
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'diagnostic_centers:all-centers' %}">Centers</a>
					</li>
					<li class="nav-item ">
						<a class="nav-link" href="{% url 'tests:all-tests' %}">Tests</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'tests:categories' %}">Categories</a>
					</li>
					<!-- <li class="nav-item">
						<a class="nav-link slide-left" href="#">
							<i class="fas fa-cart-plus"></i>
						</a>
					</li> -->

					{% if user.is_authenticated %}
					<li class="nav-item user-profile">
						<a class="nav-link d-flex dropdown-btn" href="#">
							<img src="{{ user.customer_profile.image.url }}" alt="" class="rounded-circle">
							<span class=" dropdown-toggle ml-2">{{user.username}} </span>
						</a>

						<ul class="dropdown">
							<li class="text-center">
								<img src="{{ user.customer_profile.image.url }}" alt="" class="rounded-circle">
								<p>{{ user.customer_profile.profile_name }}</p>
								<a href="{% url 'Custom_users:profile-edit' %}">
									Edit Profile
								</a>
							</li>
							<div class="dropdown-divider"></div>
							<li class="dropdown-item">
								<a href="{% url 'Custom_users:orders-by-user' %}"> View Profile</a>
							</li>
							<li class="dropdown-item">
								<a href="{% url 'Custom_users:filtered-reports-by-user' user.id %}"> Reports</a>
							</li>
							<li class="dropdown-item">
								{% comment %} <a href="{% url 'account_logout' %}"> Logout</a> {% endcomment %}
							</li>
						</ul>
					</li>
					<!-- <li class="nav-item">
						{% comment %} <a class="nav-link" href="{% url 'account_logout' %}">Logout</a> {% endcomment %}
					</li> -->
					{% else %}
					<li class="nav-item ">
						{% comment %} <a class="nav-link" href="{% url 'account_login' %}">Login</a> {% endcomment %}
					</li>
					<li class="nav-item">
						{% comment %} <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a> {% endcomment %}
					</li>
					{% endif %}

				</ul>
			</div>
		</div>
	</nav>

	<!-- <div class="add-to-cart-box" id="add-to-cart">
		<div class="card">
			<div class="card-header">
				<h5 class="card-title float-left">Lorem, ipsum dolor.</h5>
				<button type="button" class="close  slide-right">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="card-body p-4">

				<p class="item-price"> <span id="itemPrice"></span> BDT </p>

			</div>
		</div>
	</div> -->

	{% block content %} {% endblock %} {% block extra_body %} {% endblock %}

	<div class="footer text-white text-center py-3">
		<div class="w-100 text-center d-flex justify-content-center">
			{#			<div class="d-box"> Developed By</div>#}

			<div class="d-box px-2">
				{% comment %} <a class="text-white" href="{% url 'developers' %}" target="_blank" data-toggle="tooltip" {% endcomment %}
					data-placement="top" title="About Developers">About Developers</a>
			</div>

			{#			<div class="d-box px-2">#}
			{#				<a class="text-warning" href="https://www.linkedin.com/in/abdullah-al-galib" target="_blank"#}
			{#					data-toggle="tooltip" data-placement="top" title="Abdullah Al Galib">Galib</a>#}
			{#				and#}
			{#			</div>#}
			{##}
			{#			<div class="d-box">#}
			{#				<a class="text-warning" href="https://www.linkedin.com/in/sohanoor" target="_blank" data-toggle="tooltip"#}
			{#					data-placement="top" title="Sohanur Rahman">#}
			{#					Sohanur#}
			{#				</a>#}
			{#			</div>#}

		</div>
	</div>








	<script src="{% static 'js/fakeLoader.min.js' %}"></script>
	<script>
		$.fakeLoader();
		$(function () {
			$('[data-toggle="tooltip"]').tooltip()
		})
	</script>

	<script>
		$(document).ready(function () {
			$(".dropdown-btn").click(function (e) {
				e.preventDefault();
				$('.dropdown').toggle();
			});
		});
	</script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
		integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
	</script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/ok/developers.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Developers</title>
    <STYLE>A {text-decoration: none;} </STYLE>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
</head>

<body>
    <div class="container">
        <br>
        <h2>Developers and Contributors:</h2>
        <br>
        <div class="jumbotron">
            <h4>
                1. <a href="https://www.linkedin.com/in/abdullah-al-galib/" target="_blank" title="Md. Abdullah Al Galib">Galib</a> ~ (Copyright © 2019)
            </h4>

            <h4>
                2. <a href="https://www.linkedin.com/in/sohanoor" target="_blank" title="Md. Sohanur Rahman">Sohanur</a> ~ (Copyright © 2019)
            </h4>

            <h4>3. <a href="https://www.facebook.com/ahredoan" target="_blank" title="Ahsan Habib">Ahsan</a></h4>

            <h4>4. <a href="https://www.facebook.com/nazmul.0105" target="_blank" title="Md. Nazmul Hossain">Nazmul</a></h4>

            <h4>5. <a href="https://www.facebook.com/tareq.py" target="_blank" title="Mohammad Bin Qasim">Tareq</a></h4>

            <h4>6. <a href="https://www.facebook.com/masudmorshed6" target="_blank" title="Masud Morshed">Masud</a></h4>

            <h4>7. <a href="https://www.facebook.com/icerahi" target="_blank" title="Rahi Chowdory">Rahi</a></h4>

            <h4>8. <a href="https://www.facebook.com/python.m" target="_blank" title="Mohaiminul Hasan">Mohaimin</a></h4>

            <h4>9. <a href="https://www.facebook.com/rumimanzurul.hoque" target="_blank" title="Rumi Manjurul Hoque">Rumi</a></h4>
        </div>
    </div>

</body>
</html>

templates/ok/home.html
{% extends 'base.html' %}

{% block title %}Home | ODLRS{% endblock %}

{% block content %}

<div class="header-image">
    <div class="container">
        <div class="header-content">
            <h1>ONLINE TEST</h1>
            <h2>booking</h2>
            <h5>book now any kind of tests</h5>

            <a href="#welcome" class="btn"> get started <i class="fa fa-arrow-right pl-2"></i> </a>
        </div>
    </div>
</div>

<div class="welcome container text-dark" id="welcome">

    <!-- search -->
    <div class="search-box bg-dark p- my-4">

        <div class="container">
            <h3 class="text-white mb-">Search Tests</h3>

            <form class="search" action="" method="GET">
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control" name='q' placeholder="type any test's name..."
                        aria-label="Recipient's username" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-info" class="searchButton">
                            SEARCH
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>
    <!-- search end -->


    <!-- categories start -->
    {#    <h3 class="text-uppercase">Categories</h3>#}
    {#    <hr>#}
    {#    <div class="row">#}
    {#        {% for category in all_category %}#}
    {#        <div class="col-3">#}
    {#            <div class="card text-center p-5 mb-4">#}
    {#                <a href="{% url 'tests:categorise-tests' category.id %}">{{ category.category_name }}</a>#}
    {#            </div>#}
    {#        </div>#}
    {#        {% endfor %}#}
    {#    </div>#}
    <!-- categories end -->

    <h3 class="text-uppercase mt-3">all tests</h3>
    <hr>
    <!-- all tests -->
    <div class="row mt-4">
        {% for test in all_tests_paginator_data %}
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
            <div class="card test-box">
                <div class="card-title">
                    <img src="{{ test.image.url }}" class="card-img-top" alt="..." width="100%">
                </div>

                <div class="card-body pb-0">
                    <p class="card-subtitle mb-2 text-muted">{{ test.category }}</p>

                    <h6 class="">
                        <a href="{% url 'tests:test-details' test.id %}">{{ test.test_name }}</a>
                    </h6>

                    <p class="card-text">{{ test.center }}</p>
                    <p class="card-text text-dange price">Discount: <span id="price">{{ test.discount }}</span> TK</p>
                    <p class="card-text text-dange price">Price: <span id="price">{{ test.price }}</span> TK</p>
                    <!-- <p class="card-text">{{ test.active_status }}</p> -->

                    <a class="btn btn-sm order-btn text-center" href="{% url 'tests:order' test.id %}">
                        ORDER
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item">
                {% if all_tests_paginator_data.has_previous %}
                <a class="page-link" href="?page=1" aria-label="Previous">
                    <span aria-hidden="false">&laquo;</span>
                </a>
                {% endif %}

            </li>
            <li class="page-item">
                <a class="page-link" href="#">Page {{ all_tests_paginator_data.number }} of
                    {{ all_tests_paginator_data.paginator.num_pages }}</a>
            </li>
            <li class="page-item">
                {% if all_tests_paginator_data.has_next %}
                <a class="page-link" href="?page={{ all_tests_paginator_data.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
                {% endif %}
            </li>
        </ul>
    </nav>
    <!-- all tests paginator end -->
    <!-- all tests end -->
</div>



<!--
<script>
    const cartBtn = document.getElementById('cart-btn');
    const cart = document.getElementById('add-to-cart');

    cartBtn.addEventListener("click", function addItem() {
        cart.style.display = 'block'
    });
</script> -->


<!-- ///////////////////////////////// -->
<!-- <a href="#" id="seeMore">Show More</a>
    <script>
        $(document).ready(function () {
            $("div").slice(0, 3).show();
            $("#seeMore").click(function (e) {
                e.preventDefault();
                $("div:hidden").slice(0, 3).fadeIn("slow");

                if ($("div:hidden").length == 0) {
                    $("#seeMore").fadeOut("slow");
                }
            });
        })
    </script> -->
<!-- ///////////////////////////////// -->

{% endblock content %}